#!/bin/bash

#	On vides les variabls au cas où
		file=
		namefichier=
		numberofpages=
		uneven=
	
#	VARIABLES

SoftwareName="ARDentaire"
MergeAllPDF="$SoftwareName"
		MergeAllPDFdir="/tmp/mergeallpdf"
		pdgdir="$HOME/.ardentaire/pdg"

#	IN CASE OF
		mkdir -p "$MergeAllPDFdir"
		mkdir -p "$pdgdir"
		convert xc:none -page A4 "$pdgdir/blank.pdf"
		blankpage="$pdgdir/blank.pdf"
#
#
######################################################
#
		#Le Fichier aura le nom du répertoire courant
				namefichier=${PWD##*/}
				fichierfinal="$namefichier.pdf"



fn_makeeven() { # Partie du script qui rendra les PDF à nombre pair de page. #--onlyevenfile non testé

#get the number of pages
  numberofpages=`pdftk "$file" dump_data | sed -e '/NumberOfPages/!d;s/NumberOfPages: //'`

  uneven=$(($numberofpages % 2))
  if [ $uneven == 1 ]
  then
  echo -e "Impair ($numberofpages) : ajout d'une page blanche à \"$file\""
    pdftk "$file" "$blankpage" cat output "$MergeAllPDFdir"/"$file"
#    pdftk "$file" "$blankpage" cat output "$MergeAllPDF"/"$file"
  else
  echo -e "Pair ($numberofpages) : pas de modification de \"$file\""
    cp "$file" "$MergeAllPDFdir"/"$file"
    
  fi
}

fn_merging() { # Partie du script qui fusionne tous les PDF du dossier courant
echo -e "\n==> Fusion des PDFs..."
pdftk "$MergeAllPDFdir"/*.pdf output "$MergeAllPDF"/"$fichierfinal" dont_ask

echo -e "==> Suppression des fichiers temporaires..."
rm "$MergeAllPDFdir"/*
echo -e "\n      >> File $namefichier done ! <<\n"
}


fn_help() {
echo -e "
	MergeAllPDF is made for A.R.Dentaire purpose, but you can find utilities in it. Its
	dependencie is pdftk - PDF Toolkit from PDF Labs.

	It evenize all the *.pdf of the directory in a unique PDF you'll can find in
	ARDentaire/MergeAllPDF/\$name_of_the_directory


	Commands :

		--help, -h
			display this menu

		[no argument]
			as the name of the bashscripts says : it will merge all the PDF
			of the current directory, after having evenize them.

		--onlymerge
			only merge all the .PDF files of the current directory, without evenize them before.

		--onlyevenfile [file]
			only even the PDF file you define. do not forget the .pdf at the end.

		--onlyevenall
			it evenize all the odd PDF of the currentdirectory. doesnt work at the moment !" ### !
}


mkdir -p "$MergeAllPDF"

case $1 in
	"")		mergeallpdf --onlyevenall && mergeallpdf --onlymerge ;;
	--onlyevenfile)	file="$2"
			fn_makeeven
			mv "$MergeAllPDFdir"/"$file" "$file" ;; 
	--onlyevenall)	for file in *.pdf
			do 			#	DOESNT WORK
			fn_makeeven 		#	HAVE TO FIN A WAY TO MOVE BACK THE FILES,
			done ;;			#	!!! WITHOUT GENE FOR ARDENTAIRE BASHSCRIPT !!!
	--onlymerge)	fn_merging ;;
	--help|-h)	fn_help ;;
esac

exit 0
